name: "vault"
version: "0.1.0"
usage: "Get secrets from vault directly"
description: |-
  Purpose of plugin is to get secrets from vault directly and apply it on pre-deployment step
command: "$HELM_PLUGIN_DIR/bin/vault"